Repository GuessHangeul/guess-hangeul, pull requests merged in 2024-11, with the labels that each got.

#26 feat: 일반 게시판 목록 조회 기능
  .gitignore
  src/main/java/com/estsoft/guesshangeul/GuessHangeulApplication.java
  src/main/java/com/estsoft/guesshangeul/board/controller/GeneralBoardController.java
  src/main/java/com/estsoft/guesshangeul/board/dto/GeneralBoardResponse.java
  src/main/java/com/estsoft/guesshangeul/board/entity/GeneralBoard.java
  src/main/java/com/estsoft/guesshangeul/board/entity/QuizBoard.java
  src/main/java/com/estsoft/guesshangeul/board/repository/GeneralBoardRepository.java
  src/main/java/com/estsoft/guesshangeul/board/service/GeneralBoardService.java
  src/main/java/com/estsoft/guesshangeul/comment/entity/GeneralComment.java
  src/main/java/com/estsoft/guesshangeul/comment/entity/QuizComment.java
  src/main/java/com/estsoft/guesshangeul/config/JpaAuditingConfig.java
  src/main/java/com/estsoft/guesshangeul/config/SecurityConfig.java
  src/main/java/com/estsoft/guesshangeul/user/entity/Users.java
  src/test/java/com/estsoft/guesshangeul/controller/board/GeneralBoardControllerTest.java
  src/test/java/com/estsoft/guesshangeul/repository/board/GeneralBoardRepositoryTest.java
  src/test/java/com/estsoft/guesshangeul/service/board/GeneralBoardServiceTest.java
Labels: enhancement

#29 Feature/10 quiz board create read
  .idea/sqldialects.xml
  src/main/java/com/estsoft/guesshangeul/board/controller/QuizBoardController.java
  src/main/java/com/estsoft/guesshangeul/board/dto/QuizBoardCreateRequest.java
  src/main/java/com/estsoft/guesshangeul/board/dto/QuizBoardDto.java
  src/main/java/com/estsoft/guesshangeul/board/dto/QuizBoardResponse.java
  src/main/java/com/estsoft/guesshangeul/board/entity/QuizBoard.java
  src/main/java/com/estsoft/guesshangeul/board/repository/QuizBoardRepository.java
  src/main/java/com/estsoft/guesshangeul/board/service/QuizBoardService.java
  src/main/java/com/estsoft/guesshangeul/config/SecurityConfig.java
  src/main/java/com/estsoft/guesshangeul/exception/EntityAttributeDuplicateException.java
  src/main/java/com/estsoft/guesshangeul/exception/EntityNotFoundException.java
  src/main/java/com/estsoft/guesshangeul/exception/GlobalExceptionHandler.java
  src/main/java/com/estsoft/guesshangeul/exception/QuizBoardTitleDuplicateException.java
  src/main/java/com/estsoft/guesshangeul/exception/UsersNotFoundException.java
  src/main/java/com/estsoft/guesshangeul/user/dto/UsersResponse.java
  src/main/java/com/estsoft/guesshangeul/user/entity/Users.java
  src/main/java/com/estsoft/guesshangeul/user/service/UsersService.java
  src/main/resources/application.properties
  src/test/java/com/estsoft/guesshangeul/controller/board/QuizBoardControllerTest.java
  src/test/java/com/estsoft/guesshangeul/repository/board/QuizBoardRepositoryTest.java
  src/test/java/com/estsoft/guesshangeul/service/board/QuizBoardServiceTest.java
Labels: enhancement

#32 fix: Users 캐스팅 에러
  src/main/java/com/estsoft/guesshangeul/board/service/QuizBoardService.java
Labels: bug

#36 Feature/34 board delete
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminController.java
  src/main/java/com/estsoft/guesshangeul/admin/service/AdminService.java
  src/main/java/com/estsoft/guesshangeul/board/dto/QuizBoardResponse.java
  src/test/java/com/estsoft/guesshangeul/controller/admin/AdminControllerTest.java
Labels: enhancement

#47 fix: GeneralBoardResponse 생성자 누락
  src/main/java/com/estsoft/guesshangeul/board/dto/GeneralBoardResponse.java
Labels: bug

#44 Feature/41 check user duplication
  src/main/java/com/estsoft/guesshangeul/exception/GlobalExceptionHandler.java
  src/main/java/com/estsoft/guesshangeul/exception/InvalidEmailFormatException.java
  src/main/java/com/estsoft/guesshangeul/exception/InvalidInputException.java
  src/main/java/com/estsoft/guesshangeul/exception/InvalidNicknameFormatException.java
  src/main/java/com/estsoft/guesshangeul/exception/UsersEmailDuplicateException.java
  src/main/java/com/estsoft/guesshangeul/exception/UsersNicknameDuplicateException.java
  src/main/java/com/estsoft/guesshangeul/user/controller/UsersController.java
  src/main/java/com/estsoft/guesshangeul/user/dto/AddUserRequest.java
  src/main/java/com/estsoft/guesshangeul/user/dto/CheckEmailExistsRequest.java
  src/main/java/com/estsoft/guesshangeul/user/dto/CheckEmailExistsResponse.java
  src/main/java/com/estsoft/guesshangeul/user/dto/CheckNicknameExistsRequest.java
  src/main/java/com/estsoft/guesshangeul/user/dto/CheckNicknameExistsResponse.java
  src/main/java/com/estsoft/guesshangeul/user/repository/UsersRepository.java
  src/main/java/com/estsoft/guesshangeul/user/service/UsersService.java
  src/test/java/com/estsoft/guesshangeul/controller/user/UsersControllerTest.java
  src/test/java/com/estsoft/guesshangeul/service/user/UsersServiceTest.java
Labels: enhancement

#50 Feature/37 boardmanager accept reject
  .idea/modules.xml
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminController.java
  src/main/java/com/estsoft/guesshangeul/admin/dto/BoardManagerApplyResponse.java
  src/main/java/com/estsoft/guesshangeul/admin/repository/BoardManagerApplyRepository.java
  src/main/java/com/estsoft/guesshangeul/admin/service/AdminService.java
  src/main/java/com/estsoft/guesshangeul/user/repository/AuthoritiesRepository.java
  src/test/java/com/estsoft/guesshangeul/controller/admin/AdminControllerTest.java
Labels: enhancement

#57 feat: 공통 레이아웃 구현
  build.gradle
  src/main/java/com/estsoft/guesshangeul/config/ViewControllerAdvice.java
  src/main/java/com/estsoft/guesshangeul/user/dto/RoleType.java
  src/main/resources/application.properties
  src/main/resources/static/js/withdrawalModal.js
  src/main/resources/static/logo.png
  src/main/resources/templates/common/adminLayout.html
  src/main/resources/templates/common/defaultLayout.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/common/sideContentLayout.html
  src/main/resources/templates/common/sidebar.html
  src/main/resources/templates/common/withdrawalModal.html
  src/main/resources/templates/examplePage.html
Labels: enhancement

#66 fix: 회원탈퇴 모달창 로그인 여부 확인
  src/main/resources/templates/common/withdrawalModal.html
Labels: bug

#60 Feature/48 퀴즈 게시판 생성 페이지
  src/main/java/com/estsoft/guesshangeul/board/controller/BoardViewController.java
  src/main/resources/static/js/createBoard.js
  src/main/resources/templates/createBoard.html
Labels: enhancement

#64 fix: Principal 캐스팅 버그
  src/main/java/com/estsoft/guesshangeul/board/service/QuizBoardService.java
  src/test/java/com/estsoft/guesshangeul/service/board/QuizBoardServiceTest.java
Labels: bug

#68 Feature/51 admin page
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminPageController.java
  src/main/resources/static/css/admin.css
  src/main/resources/static/js/admin.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/common/sidebar.html
Labels: enhancement

#73 Feature/58 admin board page
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminPageController.java
  src/main/java/com/estsoft/guesshangeul/board/service/GeneralBoardService.java
  src/main/java/com/estsoft/guesshangeul/board/service/QuizBoardService.java
  src/main/resources/static/css/adminGeneralBoard.css
  src/main/resources/static/css/adminQuizBoard.css
  src/main/resources/static/js/adminBoard.js
  src/main/resources/static/js/adminQuizBoard.js
  src/main/resources/templates/adminGeneralBoard.html
  src/main/resources/templates/adminQuizBoard.html
  src/main/resources/templates/common/sidebar.html
Labels: enhancement

#81 홈페이지 구현
  src/main/java/com/estsoft/guesshangeul/admin/service/AdminService.java
  src/main/java/com/estsoft/guesshangeul/board/controller/BoardController.java
  src/main/java/com/estsoft/guesshangeul/board/controller/BoardViewController.java
  src/main/java/com/estsoft/guesshangeul/board/dto/BoardResponse.java
  src/main/java/com/estsoft/guesshangeul/board/repository/GeneralBoardRepository.java
  src/main/java/com/estsoft/guesshangeul/board/service/BoardService.java
  src/main/java/com/estsoft/guesshangeul/comment/repository/GeneralCommentRepository.java
  src/main/java/com/estsoft/guesshangeul/comment/repository/QuizCommentRepository.java
  src/main/java/com/estsoft/guesshangeul/post/controller/GeneralPostController.java
  src/main/java/com/estsoft/guesshangeul/post/controller/QuizPostController.java
  src/main/java/com/estsoft/guesshangeul/post/dto/AddGeneralPostRequest.java
  src/main/java/com/estsoft/guesshangeul/post/dto/PostResponse.java
  src/main/java/com/estsoft/guesshangeul/post/repository/GeneralPostRepository.java
  src/main/java/com/estsoft/guesshangeul/post/repository/QuizPostRepository.java
  src/main/java/com/estsoft/guesshangeul/post/service/GeneralPostService.java
  src/main/resources/static/css/postItem.css
  src/main/resources/templates/common/boardCard.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/common/postItem.html
  src/main/resources/templates/index.html
Labels: enhancement

#93 fix: "병합 후 오류 해결"
  src/main/java/com/estsoft/guesshangeul/post/repository/QuizPostRepository.java
  src/main/java/com/estsoft/guesshangeul/post/service/QuizPostService.java
Labels: bug

#96 fix: "병합 후 오류 해결"
  src/main/java/com/estsoft/guesshangeul/post/service/QuizPostService.java
Labels: bug

#95 게시판 페이지 구현
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminPageController.java
  src/main/java/com/estsoft/guesshangeul/board/controller/BoardViewController.java
  src/main/java/com/estsoft/guesshangeul/post/controller/GeneralPostController.java
  src/main/java/com/estsoft/guesshangeul/post/controller/QuizPostController.java
  src/main/java/com/estsoft/guesshangeul/post/dto/GeneralPostWithCommentCountInterface.java
  src/main/java/com/estsoft/guesshangeul/post/dto/GeneralPostWithCommentCountResponse.java
  src/main/java/com/estsoft/guesshangeul/post/dto/QuizPostWithCommentCountInterface.java
  src/main/java/com/estsoft/guesshangeul/post/dto/QuizPostWithCommentCountResponse.java
  src/main/java/com/estsoft/guesshangeul/post/repository/GeneralPostRepository.java
  src/main/java/com/estsoft/guesshangeul/post/repository/QuizPostRepository.java
  src/main/java/com/estsoft/guesshangeul/post/service/GeneralPostService.java
  src/main/java/com/estsoft/guesshangeul/post/service/QuizPostService.java
  src/main/resources/static/js/boardPage.js
  src/main/resources/templates/adminGeneralBoard.html
  src/main/resources/templates/adminQuizBoard.html
  src/main/resources/templates/common/postItem.html
  src/main/resources/templates/generalBoard.html
  src/main/resources/templates/quizBoard.html
Labels: enhancement

#105 Feature/100 swagger
  build.gradle
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminController.java
  src/main/java/com/estsoft/guesshangeul/admin/dto/BoardManagerApplyResponse.java
  src/main/java/com/estsoft/guesshangeul/config/SwaggerConfig.java
  src/main/java/com/estsoft/guesshangeul/post/dto/GeneralPostResponse.java
  src/main/java/com/estsoft/guesshangeul/post/dto/QuizPostResponse.java
  src/main/java/com/estsoft/guesshangeul/user/dto/UsersResponse.java
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/adminBoard.js
  src/main/resources/static/js/adminQuizBoard.js
Labels: enhancement

#107 게시판 생성 버튼 적용
  src/main/java/com/estsoft/guesshangeul/board/controller/BoardViewController.java
  src/main/java/com/estsoft/guesshangeul/board/repository/GeneralBoardRepository.java
  src/main/java/com/estsoft/guesshangeul/board/repository/QuizBoardRepository.java
  src/main/java/com/estsoft/guesshangeul/board/service/GeneralBoardService.java
  src/main/java/com/estsoft/guesshangeul/board/service/QuizBoardService.java
  src/main/resources/templates/generalBoard.html
  src/main/resources/templates/quizBoard.html
Labels: enhancement

#111 관리자 - 일반,퀴즈 게시글 검색
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminPageController.java
  src/main/resources/static/css/adminGeneralBoard.css
  src/main/resources/static/css/adminQuizBoard.css
  src/main/resources/static/js/adminBoard.js
  src/main/resources/static/js/adminQuizBoard.js
  src/main/resources/templates/adminGeneralBoard.html
  src/main/resources/templates/adminQuizBoard.html
Labels: enhancement

#118 fix: 집현전 신청 에러 수정
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminBoardController.java
  src/main/java/com/estsoft/guesshangeul/admin/controller/BoardManagerApplyController.java
  src/main/java/com/estsoft/guesshangeul/admin/entity/BoardManagerApply.java
  src/main/java/com/estsoft/guesshangeul/user/controller/UsersController.java
  src/main/java/com/estsoft/guesshangeul/user/service/UsersService.java
  src/main/java/com/estsoft/guesshangeul/userrank/controller/ViewRankupRequestController.java
  src/main/java/com/estsoft/guesshangeul/userrank/service/ViewRankupRequestService.java
  src/main/resources/templates/RankupRequestList.html
Labels: bug

#114 랭킹 페이지 적용
  .idea/modules/guess-hangeul.main.iml
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminBoardController.java
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminPageController.java
  src/main/java/com/estsoft/guesshangeul/admin/service/AdminBoardService.java
  src/main/java/com/estsoft/guesshangeul/config/ViewControllerAdvice.java
  src/main/java/com/estsoft/guesshangeul/user/dto/UsersResponse.java
  src/main/java/com/estsoft/guesshangeul/user/repository/UsersRepository.java
  src/main/java/com/estsoft/guesshangeul/user/service/UsersService.java
  src/main/java/com/estsoft/guesshangeul/userrank/controller/RankingPageController.java
  src/main/resources/static/css/ranking.css
  src/main/resources/static/js/scoreUpdater.js
  src/main/resources/templates/common/sideContentLayout.html
  src/main/resources/templates/ranking.html
Labels: enhancement

#119 관리자 집현전 관리 페이지
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminPageController.java
  src/main/java/com/estsoft/guesshangeul/user/controller/UsersController.java
  src/main/java/com/estsoft/guesshangeul/user/service/UsersService.java
  src/main/java/com/estsoft/guesshangeul/userrank/controller/ViewRankupRequestController.java
  src/main/java/com/estsoft/guesshangeul/userrank/dto/ViewRankupRequestResponse.java
  src/main/java/com/estsoft/guesshangeul/userrank/repository/BoardManagerRepository.java
  src/main/resources/static/js/adminBoardManager.js
  src/main/resources/templates/adminBoardManager.html
  src/main/resources/templates/common/sidebar.html
Labels: enhancement

#120 Fix: 집현전 신청자 조회 수정
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminPageController.java
  src/main/java/com/estsoft/guesshangeul/userrank/controller/ViewRankupRequestController.java
  src/main/java/com/estsoft/guesshangeul/userrank/service/ViewRankupRequestService.java
  src/main/resources/static/js/adminBoardManager.js
  src/main/resources/templates/adminBoardManager.html
Labels: enhancement

#122 feat: "유저 검색 추가"
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminBoardController.java
  src/main/java/com/estsoft/guesshangeul/admin/controller/AdminPageController.java
  src/main/java/com/estsoft/guesshangeul/admin/service/AdminBoardService.java
  src/main/java/com/estsoft/guesshangeul/user/repository/UsersRepository.java
  src/main/resources/static/js/admin.js
  src/main/resources/templates/admin.html
Labels: enhancement

#128 feat: 정답 확인, 정답 공개 기능
  src/main/resources/static/js/quizPostPage.js
  src/main/resources/templates/quizPostPage.html
Labels: enhancement

#131 Feature/94 readme fix
  README.md
  img/게시판 생성.png
  img/계정 찾기.png
  img/관리자 권한.png
  img/관리자유저.png
  img/관리자일반.png
  img/관리자집현전.png
  img/관리자퀴즈.png
  img/랭킹.png
  img/로그인.png
  img/문제 게시판.png
  img/문제게시글.png
  img/비밀번호 변경.png
  img/일반 게시판.png
  img/일반게시글.png
  img/일반게시글수정.png
  img/일반게시글작성.png
  img/집현전신청.png
  img/홈일반.png
  img/회원가입.png
Labels: documentation

#132 fix: "readme 화면설계 수정"
  README.md
  img/게시판생성.png
  img/계정찾기.png
  img/관리자권한.png
  img/기능정의서.png
  img/문제게시판.png
  img/비밀번호변경.png
  img/일반게시판.png
Labels: documentation

#133 fix: "집현전 신청 수정"
  src/main/java/com/estsoft/guesshangeul/userrank/controller/RankingPageController.java
  src/main/resources/templates/NoBoardManager.html
Labels: enhancement

#135 fix: "readme 수정"
  README.md
  img/문제게시글수정.png
  img/문제게시글추가.png
Labels: documentation

#137 fix: "readme 이미지 추가"
  README.md
  img/비밀번호재설정.png
  img/재설정메일.png
Labels: documentation
